
import __ASTRO_IMAGE_IMPORT_2qe9R from "./images/example-mdx-article/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-mdx-article.mdx";
import __ASTRO_IMAGE_IMPORT_Z1KqsNe from "./images/example-markdown-article/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-markdown-article.md";
import __ASTRO_IMAGE_IMPORT_2mUCtz from "./images/example-markdown-article/explanation.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-markdown-article.md";
import __ASTRO_IMAGE_IMPORT_P2Jin from "./images/install-setup-haproxy/service.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md";
import __ASTRO_IMAGE_IMPORT_1llv6x from "./images/install-setup-haproxy/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md";
import __ASTRO_IMAGE_IMPORT_Nthl0 from "./images/resource-definition-in-openshift/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fresource-definition-in-openshift.md";
import __ASTRO_IMAGE_IMPORT_rB8fC from "./images/pro-accountant/accnt.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpro-accountant.mdx";
import __ASTRO_IMAGE_IMPORT_Z27euY2 from "./images/budget-wise/finance_app_concept.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffinance-app.mdx";
import __ASTRO_IMAGE_IMPORT_1qSETc from "./images/install-setup-haproxy/dashboard.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md";
import __ASTRO_IMAGE_IMPORT_Qs5L1 from "./images/install-setup-haproxy/dashboardaktif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md";
export default new Map([["./images/example-mdx-article/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-mdx-article.mdx", __ASTRO_IMAGE_IMPORT_2qe9R], ["./images/example-markdown-article/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-markdown-article.md", __ASTRO_IMAGE_IMPORT_Z1KqsNe], ["./images/example-markdown-article/explanation.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexample-markdown-article.md", __ASTRO_IMAGE_IMPORT_2mUCtz], ["./images/install-setup-haproxy/service.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md", __ASTRO_IMAGE_IMPORT_P2Jin], ["./images/install-setup-haproxy/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md", __ASTRO_IMAGE_IMPORT_1llv6x], ["./images/resource-definition-in-openshift/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fresource-definition-in-openshift.md", __ASTRO_IMAGE_IMPORT_Nthl0], ["./images/pro-accountant/accnt.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpro-accountant.mdx", __ASTRO_IMAGE_IMPORT_rB8fC], ["./images/budget-wise/finance_app_concept.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffinance-app.mdx", __ASTRO_IMAGE_IMPORT_Z27euY2], ["./images/install-setup-haproxy/dashboard.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md", __ASTRO_IMAGE_IMPORT_1qSETc], ["./images/install-setup-haproxy/dashboardaktif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FInstall-setup-haproxy.md", __ASTRO_IMAGE_IMPORT_Qs5L1]]);
		